export const data = [
  {
    id: 0,
    shopName: "embrace robust portals",
    ownerName: "Ms. Brooke Hane V",
    category: "Delivery",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Pfannerstill Falls",
    city: "Angelafield",
    state: "Kentucky",
    phone: "868.656.8812 x005",
    email: "Hettie76@gmail.com",
    website: "https://zealous-renaissance.name",
    img: "https://loremflickr.com/640/380/business?lock=2690674702942208",
    banner: "https://loremflickr.com/1200/380/business?lock=1552970365796352",
    discription:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
  },
  {
    id: 1,
    shopName: "reintermediate clicks-and-mortar networks",
    ownerName: "Gerard Ankunding",
    category: "Restaurant",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Waters Falls",
    city: "Windlerboro",
    state: "Rhode Island",
    phone: "(213) 817-4262 x254",
    email: "Jeffery_Hermann27@hotmail.com",
    website: "https://sinful-input.biz/",
    img: "https://loremflickr.com/640/380/business?lock=1065725770858496",
    banner: "https://loremflickr.com/1200/380/business?lock=7394352640819200",
    discription:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
  },
  {
    id: 2,
    shopName: "generate user-centric mindshare",
    ownerName: "Percy Terry",
    category: "Restaurant",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Schimmel Circle",
    city: "East Melany",
    state: "Wyoming",
    phone: "296.815.3360 x75051",
    email: "Maverick.Schinner20@gmail.com",
    website: "https://precious-feature.name",
    img: "https://loremflickr.com/640/380/business?lock=6623319361060864",
    banner: "https://loremflickr.com/1200/380/business?lock=3919213559283712",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 3,
    shopName: "target viral convergence",
    ownerName: "Levi Wisozk",
    category: "Delivery",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Cartwright Glen",
    city: "Fort Victoria",
    state: "Maine",
    phone: "(311) 349-4604 x581",
    email: "Clifford_Hartmann@yahoo.com",
    website: "https://utilized-ashtray.name",
    img: "https://loremflickr.com/640/380/business?lock=4984639751979008",
    banner: "https://loremflickr.com/1200/380/business?lock=6202252272336896",
    discription:
      "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
  },
  {
    id: 4,
    shopName: "monetize clicks-and-mortar methodologies",
    ownerName: "Arlene Bergstrom",
    category: "Dry Cleaning",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Homenick Knoll",
    city: "West Ginaview",
    state: "North Carolina",
    phone: "(908) 959-0485 x3414",
    email: "Austin.Smitham@yahoo.com",
    website: "https://immaculate-clasp.info",
    img: "https://loremflickr.com/640/380/business?lock=7833029613453312",
    banner: "https://loremflickr.com/1200/380/business?lock=2664719582232576",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 5,
    shopName: "strategize cross-media portals",
    ownerName: "Sean Johnson",
    category: "Delivery",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Brakus Via",
    city: "Monroe",
    state: "Nebraska",
    phone: "(612) 410-2337",
    email: "Donnie_Corkery@hotmail.com",
    website: "https://zigzag-chicken.com",
    img: "https://loremflickr.com/640/380/business?lock=7928606250500096",
    banner: "https://loremflickr.com/1200/380/business?lock=210242084274176",
    discription:
      "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
  },
  {
    id: 6,
    shopName: "innovate B2C applications",
    ownerName: "Lori Morissette",
    category: "Dry Cleaning",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Bogan Prairie",
    city: "Turnerfurt",
    state: "Montana",
    phone: "(336) 599-4296",
    email: "Victoria.Rippin82@gmail.com",
    website: "https://insecure-conductor.net/",
    img: "https://loremflickr.com/640/380/business?lock=3534051321315328",
    banner: "https://loremflickr.com/1200/380/business?lock=243266891022336",
    discription:
      "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
  },
  {
    id: 7,
    shopName: "disintermediate B2C synergies",
    ownerName: "Dr. Cecil Waters",
    category: "Restaurant",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Victoria Road",
    city: "Warwick",
    state: "Oregon",
    phone: "1-783-822-5432 x0107",
    email: "Zoe.Cummerata30@yahoo.com",
    website: "https://spirited-bull.org",
    img: "https://loremflickr.com/640/380/business?lock=4791228365275136",
    banner: "https://loremflickr.com/1200/380/business?lock=7158796629573632",
    discription:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
  },
  {
    id: 8,
    shopName: "scale cross-platform schemas",
    ownerName: "Otis Franey",
    category: "Auto Services",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Glover Key",
    city: "Danielfield",
    state: "South Dakota",
    phone: "947.910.2866 x30064",
    email: "Stanton_McGlynn@gmail.com",
    website: "https://helpless-dude.org",
    img: "https://loremflickr.com/640/380/business?lock=5141246968332288",
    banner: "https://loremflickr.com/1200/380/business?lock=2258193023500288",
    discription:
      "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
  },
  {
    id: 9,
    shopName: "scale efficient solutions",
    ownerName: "Pamela Kovacek",
    category: "Auto Services",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Alfredo Roads",
    city: "Port Darby",
    state: "Oklahoma",
    phone: "756.761.7689",
    email: "Sophia_Schroeder@yahoo.com",
    website: "https://pointed-picnic.org/",
    img: "https://loremflickr.com/640/380/business?lock=8784193892909056",
    banner: "https://loremflickr.com/1200/380/business?lock=96253209739264",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 10,
    shopName: "empower B2B lifetime value",
    ownerName: "Archie Cruickshank III",
    category: "Plumbing",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Schimmel Lodge",
    city: "Allentown",
    state: "Maine",
    phone: "(906) 427-7250 x898",
    email: "Edwin_Rolfson@gmail.com",
    website: "https://parched-attempt.org/",
    img: "https://loremflickr.com/640/380/business?lock=1977247730761728",
    banner: "https://loremflickr.com/1200/380/business?lock=3608662018883584",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 11,
    shopName: "exploit leading-edge architectures",
    ownerName: "Cornelius Zulauf V",
    category: "Delivery",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Mayra Mountains",
    city: "South Andrewboro",
    state: "Arizona",
    phone: "861.637.5468 x49061",
    email: "Judah_Pfeffer@hotmail.com",
    website: "https://surprised-progenitor.info",
    img: "https://loremflickr.com/640/380/business?lock=6192040371027968",
    banner: "https://loremflickr.com/1200/380/business?lock=1214800830922752",
    discription:
      "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
  },
  {
    id: 12,
    shopName: "empower robust mindshare",
    ownerName: "Dr. Jermaine Hilpert",
    category: "Home Services",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Lauretta Walk",
    city: "Torpburgh",
    state: "Kansas",
    phone: "1-256-581-1410 x39044",
    email: "Delores_Bradtke43@yahoo.com",
    website: "https://sudden-age.net",
    img: "https://loremflickr.com/640/380/business?lock=6684867135799296",
    banner: "https://loremflickr.com/1200/380/business?lock=1708844975652864",
    discription:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
  },
  {
    id: 13,
    shopName: "e-enable web-enabled paradigms",
    ownerName: "Mrs. Annie Wyman",
    category: "Auto Services",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Mary Street",
    city: "Krajcikfurt",
    state: "Colorado",
    phone: "693.546.1123 x880",
    email: "Kendall.Hammes73@gmail.com",
    website: "https://bustling-carload.org",
    img: "https://loremflickr.com/640/380/business?lock=8610920290844672",
    banner: "https://loremflickr.com/1200/380/business?lock=5119923971948544",
    discription:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
  },
  {
    id: 14,
    shopName: "e-enable value-added interfaces",
    ownerName: "Bert Robel",
    category: "Auto Services",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Feest Overpass",
    city: "Mosciskiland",
    state: "Maryland",
    phone: "(606) 868-7186 x304",
    email: "Delaney21@yahoo.com",
    website: "https://oval-antiquity.name/",
    img: "https://loremflickr.com/640/380/business?lock=4069595140849664",
    banner: "https://loremflickr.com/1200/380/business?lock=2235138599550976",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 15,
    shopName: "synergize rich functionalities",
    ownerName: "Mrs. Kayla Padberg",
    category: "Auto Services",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "William Street",
    city: "Sydneeside",
    state: "Arizona",
    phone: "897.897.3728 x440",
    email: "Kory.Harber26@gmail.com",
    website: "https://brown-aide.name",
    img: "https://loremflickr.com/640/380/business?lock=4247992378851328",
    banner: "https://loremflickr.com/1200/380/business?lock=1366709290139648",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 16,
    shopName: "enhance scalable markets",
    ownerName: "Fannie Champlin",
    category: "Delivery",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Keeling Parks",
    city: "Morissettetown",
    state: "Delaware",
    phone: "(325) 521-9210 x822",
    email: "Trudie.Bosco@hotmail.com",
    website: "https://jubilant-priority.name/",
    img: "https://loremflickr.com/640/380/business?lock=4167468249513984",
    banner: "https://loremflickr.com/1200/380/business?lock=54889059188736",
    discription:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
  },
  {
    id: 17,
    shopName: "extend magnetic synergies",
    ownerName: "Daniel Ankunding",
    category: "Auto Services",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Birch Close",
    city: "Bruenville",
    state: "Nevada",
    phone: "332-279-5063 x362",
    email: "Marina_Konopelski80@hotmail.com",
    website: "https://accurate-nourishment.net/",
    img: "https://loremflickr.com/640/380/business?lock=88129035829248",
    banner: "https://loremflickr.com/1200/380/business?lock=5521429063794688",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 18,
    shopName: "scale magnetic schemas",
    ownerName: "Felix Kassulke",
    category: "Delivery",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Spring Gardens",
    city: "Lueilwitzstad",
    state: "Georgia",
    phone: "(832) 875-6295 x066",
    email: "Reanna41@gmail.com",
    website: "https://teeming-maple.biz/",
    img: "https://loremflickr.com/640/380/business?lock=8284820566179840",
    banner: "https://loremflickr.com/1200/380/business?lock=6399998008754176",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 19,
    shopName: "exploit impactful paradigms",
    ownerName: "Billy Braun",
    category: "Restaurant",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Nikolaus Club",
    city: "North Augustus",
    state: "New Jersey",
    phone: "213.952.1807 x1005",
    email: "Bell_Bayer4@yahoo.com",
    website: "https://slow-progenitor.com/",
    img: "https://loremflickr.com/640/380/business?lock=2983111495254016",
    banner: "https://loremflickr.com/1200/380/business?lock=7938075902607360",
    discription:
      "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
  },
  {
    id: 20,
    shopName: "harness best-of-breed partnerships",
    ownerName: "Loren Konopelski",
    category: "Dry Cleaning",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Efren Pike",
    city: "New Jedediah",
    state: "New Jersey",
    phone: "1-388-974-3238",
    email: "Mohamed_Kunde60@hotmail.com",
    website: "https://regular-morbid.name",
    img: "https://loremflickr.com/640/380/business?lock=1079252696956928",
    banner: "https://loremflickr.com/1200/380/business?lock=1260923819917312",
    discription:
      "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
  },
  {
    id: 21,
    shopName: "seize viral synergies",
    ownerName: "Lee Schiller",
    category: "Restaurant",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Welch Ville",
    city: "Arnohaven",
    state: "Washington",
    phone: "1-238-590-3652 x101",
    email: "Alexanne.Daniel23@yahoo.com",
    website: "https://decisive-visual.net/",
    img: "https://loremflickr.com/640/380/business?lock=3343575058219008",
    banner: "https://loremflickr.com/1200/380/business?lock=2435954425987072",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 22,
    shopName: "architect integrated convergence",
    ownerName: "Dr. Doris Moore-Parisian",
    category: "Home Services",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Jeramy Rapid",
    city: "Yundtworth",
    state: "Kentucky",
    phone: "(493) 493-5623 x7637",
    email: "Lionel87@gmail.com",
    website: "https://energetic-deed.com",
    img: "https://loremflickr.com/640/380/business?lock=3024269908901888",
    banner: "https://loremflickr.com/1200/380/business?lock=3204748081627136",
    discription:
      "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
  },
  {
    id: 23,
    shopName: "incentivize B2C niches",
    ownerName: "Darrin Lang",
    category: "Plumbing",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Eliezer Locks",
    city: "Lake Kendallbury",
    state: "California",
    phone: "(579) 427-8296 x5832",
    email: "Lennie.Wunsch42@gmail.com",
    website: "https://direct-taxicab.biz/",
    img: "https://loremflickr.com/640/380/business?lock=4022885467291648",
    banner: "https://loremflickr.com/1200/380/business?lock=6327737488769024",
    discription:
      "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
  },
  {
    id: 24,
    shopName: "matrix efficient e-commerce",
    ownerName: "Jackie Wuckert",
    category: "Auto Services",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Ebert Crossroad",
    city: "Fort Richardworth",
    state: "Idaho",
    phone: "(416) 667-9437 x731",
    email: "Christy19@gmail.com",
    website: "https://agile-mine.info",
    img: "https://loremflickr.com/640/380/business?lock=5627122726993920",
    banner: "https://loremflickr.com/1200/380/business?lock=5043244576538624",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 25,
    shopName: "e-enable transparent functionalities",
    ownerName: "Jim Medhurst-Hammes",
    category: "Restaurant",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Llewellyn Spur",
    city: "New Perryland",
    state: "Oregon",
    phone: "518-338-4728",
    email: "Katharina80@gmail.com",
    website: "https://threadbare-colonization.com/",
    img: "https://loremflickr.com/640/380/business?lock=7591582417027072",
    banner: "https://loremflickr.com/1200/380/business?lock=531049595535360",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 26,
    shopName: "incubate user-centric solutions",
    ownerName: "Felix Johnson",
    category: "Home Services",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Swift Courts",
    city: "Zulaufview",
    state: "Missouri",
    phone: "(691) 541-5857",
    email: "Evan_Labadie@hotmail.com",
    website: "https://judicious-columnist.name",
    img: "https://loremflickr.com/640/380/business?lock=4833122042511360",
    banner: "https://loremflickr.com/1200/380/business?lock=6161593840697344",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 27,
    shopName: "redefine compelling portals",
    ownerName: "Alexander Nitzsche",
    category: "Delivery",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Major Hill",
    city: "Genesisshire",
    state: "Alabama",
    phone: "1-910-741-3302 x442",
    email: "Thora.OConner@gmail.com",
    website: "https://powerless-metronome.net/",
    img: "https://loremflickr.com/640/380/business?lock=5341480031879168",
    banner: "https://loremflickr.com/1200/380/business?lock=4326465243971584",
    discription:
      "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
  },
  {
    id: 28,
    shopName: "envisioneer integrated interfaces",
    ownerName: "Fredrick Mayer I",
    category: "Plumbing",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Osvaldo Meadow",
    city: "Lake Alexannestead",
    state: "Alabama",
    phone: "627.495.0470",
    email: "Cale.Schiller87@hotmail.com",
    website: "https://mellow-analogue.com",
    img: "https://loremflickr.com/640/380/business?lock=1929074528223232",
    banner: "https://loremflickr.com/1200/380/business?lock=2449725309583360",
    discription:
      "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
  },
  {
    id: 29,
    shopName: "target ubiquitous channels",
    ownerName: "Terrance Douglas",
    category: "Plumbing",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Dasia Avenue",
    city: "Lake Monroecester",
    state: "North Carolina",
    phone: "1-832-470-6990 x2354",
    email: "Arden_Simonis@gmail.com",
    website: "https://worthless-barbecue.com/",
    img: "https://loremflickr.com/640/380/business?lock=2379644439363584",
    banner: "https://loremflickr.com/1200/380/business?lock=4603777080360960",
    discription:
      "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
  },
  {
    id: 30,
    shopName: "incubate extensible communities",
    ownerName: "Shelia Blick",
    category: "Delivery",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Walsh Knoll",
    city: "Roanoke",
    state: "Rhode Island",
    phone: "250-882-4719",
    email: "Jameson64@hotmail.com",
    website: "https://greedy-tailspin.name",
    img: "https://loremflickr.com/640/380/business?lock=4202431963463680",
    banner: "https://loremflickr.com/1200/380/business?lock=8292134224396288",
    discription:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
  },
  {
    id: 31,
    shopName: "grow transparent networks",
    ownerName: "Dominick White",
    category: "Auto Services",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Benedict Track",
    city: "Elyria",
    state: "Montana",
    phone: "982.523.4195 x527",
    email: "Jess0@gmail.com",
    website: "https://better-rations.name",
    img: "https://loremflickr.com/640/380/business?lock=2879951799844864",
    banner: "https://loremflickr.com/1200/380/business?lock=19736427495424",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 32,
    shopName: "extend scalable solutions",
    ownerName: "Leigh Kunze",
    category: "Delivery",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "S High Street",
    city: "Visalia",
    state: "Florida",
    phone: "1-830-370-9139",
    email: "Isadore70@hotmail.com",
    website: "https://cultured-bidet.info/",
    img: "https://loremflickr.com/640/380/business?lock=4242287630483456",
    banner: "https://loremflickr.com/1200/380/business?lock=2101178458439680",
    discription:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
  },
  {
    id: 33,
    shopName: "target mission-critical methodologies",
    ownerName: "Monica Kemmer",
    category: "Home Services",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Lynch Stravenue",
    city: "Spring Hill",
    state: "Hawaii",
    phone: "(524) 392-8919 x790",
    email: "Melody_VonRueden55@yahoo.com",
    website: "https://unnatural-poor.org/",
    img: "https://loremflickr.com/640/380/business?lock=1246775704813568",
    banner: "https://loremflickr.com/1200/380/business?lock=880543124160512",
    discription:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
  },
  {
    id: 34,
    shopName: "mesh web-enabled infrastructures",
    ownerName: "Antonia Quigley",
    category: "Restaurant",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Murphy Bridge",
    city: "Kobychester",
    state: "Alaska",
    phone: "722.372.8337 x5041",
    email: "Kylee.Tromp83@yahoo.com",
    website: "https://neglected-embellishment.com",
    img: "https://loremflickr.com/640/380/business?lock=4052096921894912",
    banner: "https://loremflickr.com/1200/380/business?lock=5562278822805504",
    discription:
      "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
  },
  {
    id: 35,
    shopName: "empower web-enabled synergies",
    ownerName: "Miss Lydia Smith",
    category: "Dry Cleaning",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Wilford Vista",
    city: "New Rossport",
    state: "Mississippi",
    phone: "(276) 847-9112 x2211",
    email: "Turner33@hotmail.com",
    website: "https://faraway-trace.name",
    img: "https://loremflickr.com/640/380/business?lock=119870318444544",
    banner: "https://loremflickr.com/1200/380/business?lock=8681438509531136",
    discription:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
  },
  {
    id: 36,
    shopName: "innovate plug-and-play models",
    ownerName: "Cathy Dach",
    category: "Home Services",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Green Street",
    city: "New Narcisofield",
    state: "Virginia",
    phone: "562.665.4505 x8956",
    email: "Asia32@hotmail.com",
    website: "https://grubby-afternoon.name",
    img: "https://loremflickr.com/640/380/business?lock=4663266756263936",
    banner: "https://loremflickr.com/1200/380/business?lock=7888458932551680",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 37,
    shopName: "incubate efficient deliverables",
    ownerName: "Ervin Kirlin",
    category: "Auto Services",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Mabelle Valleys",
    city: "West Daisyshire",
    state: "Massachusetts",
    phone: "(746) 754-6042 x8016",
    email: "Deanna.Tillman@hotmail.com",
    website: "https://putrid-lunch.org",
    img: "https://loremflickr.com/640/380/business?lock=4459708509323264",
    banner: "https://loremflickr.com/1200/380/business?lock=6033283143958528",
    discription:
      "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
  },
  {
    id: 38,
    shopName: "benchmark value-added models",
    ownerName: "Sarah Schumm II",
    category: "Restaurant",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Barn Close",
    city: "Naderview",
    state: "Montana",
    phone: "(540) 896-2449 x68937",
    email: "Vada.Ledner@gmail.com",
    website: "https://candid-veterinarian.net",
    img: "https://loremflickr.com/640/380/business?lock=204282175422464",
    banner: "https://loremflickr.com/1200/380/business?lock=1750261651472384",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 39,
    shopName: "matrix e-business lifetime value",
    ownerName: "Sonya Olson",
    category: "Dry Cleaning",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "The Ridings",
    city: "West Gia",
    state: "Ohio",
    phone: "486-829-2788",
    email: "Juanita_Hilpert@hotmail.com",
    website: "https://dazzling-copywriter.biz/",
    img: "https://loremflickr.com/640/380/business?lock=5785373521215488",
    banner: "https://loremflickr.com/1200/380/business?lock=6162974798512128",
    discription:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
  },
  {
    id: 40,
    shopName: "harness user-centric blockchains",
    ownerName: "Harry Kautzer",
    category: "Restaurant",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Fisher Rapid",
    city: "Glen Burnie",
    state: "West Virginia",
    phone: "(373) 787-0678 x11786",
    email: "Leilani.West21@hotmail.com",
    website: "https://rubbery-water.info",
    img: "https://loremflickr.com/640/380/business?lock=469804758597632",
    banner: "https://loremflickr.com/1200/380/business?lock=8165321345073152",
    discription:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
  },
  {
    id: 41,
    shopName: "enable visionary networks",
    ownerName: "Nichole Green",
    category: "Delivery",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Kamille Spurs",
    city: "Schaeferberg",
    state: "Arizona",
    phone: "309.464.3302",
    email: "Demario.Olson@yahoo.com",
    website: "https://funny-widow.net",
    img: "https://loremflickr.com/640/380/business?lock=3424591747743744",
    banner: "https://loremflickr.com/1200/380/business?lock=8996885410873344",
    discription:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
  },
  {
    id: 42,
    shopName: "target transparent partnerships",
    ownerName: "Jim Hagenes",
    category: "Delivery",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Grant Harbors",
    city: "Lake Dereck",
    state: "Idaho",
    phone: "761-648-2307 x5189",
    email: "Jeramy_Rutherford@hotmail.com",
    website: "https://ruddy-plum.net/",
    img: "https://loremflickr.com/640/380/business?lock=7851657488498688",
    banner: "https://loremflickr.com/1200/380/business?lock=8087944820686848",
    discription:
      "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
  },
  {
    id: 43,
    shopName: "synergize synergistic bandwidth",
    ownerName: "Jeannie Wintheiser-Jones",
    category: "Dry Cleaning",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Ila Rue",
    city: "Jaimeburgh",
    state: "West Virginia",
    phone: "(221) 792-3457",
    email: "Greyson_Koch-Aufderhar89@gmail.com",
    website: "https://considerate-servant.com",
    img: "https://loremflickr.com/640/380/business?lock=8328718852292608",
    banner: "https://loremflickr.com/1200/380/business?lock=2289319496646656",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 44,
    shopName: "incubate cutting-edge initiatives",
    ownerName: "Edith Leffler",
    category: "Auto Services",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Elm Road",
    city: "East Geovanyside",
    state: "Minnesota",
    phone: "(471) 630-5803 x29323",
    email: "Jaqueline.Gutmann48@gmail.com",
    website: "https://salty-instrumentalist.org",
    img: "https://loremflickr.com/640/380/business?lock=6481666451177472",
    banner: "https://loremflickr.com/1200/380/business?lock=2668311716298752",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 45,
    shopName: "utilize efficient interfaces",
    ownerName: "Elizabeth Cassin",
    category: "Auto Services",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Moor Lane",
    city: "Louisville/Jefferson County",
    state: "Texas",
    phone: "(967) 939-5228",
    email: "Kellen.Kuhlman91@hotmail.com",
    website: "https://comfortable-loafer.info/",
    img: "https://loremflickr.com/640/380/business?lock=5269712000778240",
    banner: "https://loremflickr.com/1200/380/business?lock=995808231030784",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 46,
    shopName: "seize user-centric lifetime value",
    ownerName: "Matt Littel",
    category: "Dry Cleaning",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Will Dam",
    city: "Port Wilbert",
    state: "Missouri",
    phone: "280.357.2996 x5545",
    email: "Everette_Dicki@yahoo.com",
    website: "https://decent-campaigning.info/",
    img: "https://loremflickr.com/640/380/business?lock=3579001111052288",
    banner: "https://loremflickr.com/1200/380/business?lock=1589235807158272",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 47,
    shopName: "leverage 24/365 eyeballs",
    ownerName: "Grant Hauck",
    category: "Auto Services",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Rae Viaduct",
    city: "Oceanefort",
    state: "Colorado",
    phone: "(703) 905-5438 x781",
    email: "Maymie_Orn64@yahoo.com",
    website: "https://downright-aide.biz/",
    img: "https://loremflickr.com/640/380/business?lock=473893397594112",
    banner: "https://loremflickr.com/1200/380/business?lock=3805534675271680",
    discription:
      "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
  },
  {
    id: 48,
    shopName: "extend end-to-end mindshare",
    ownerName: "Jon Schulist",
    category: "Delivery",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Langworth Corner",
    city: "Jeweltown",
    state: "Nevada",
    phone: "1-722-629-4707 x32887",
    email: "Karlee74@hotmail.com",
    website: "https://squeaky-interior.net/",
    img: "https://loremflickr.com/640/380/business?lock=4754225745625088",
    banner: "https://loremflickr.com/1200/380/business?lock=7274571547803648",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 49,
    shopName: "incubate collaborative action-items",
    ownerName: "Anita Rempel",
    category: "Auto Services",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Breitenberg Shoal",
    city: "West Sibyl",
    state: "South Dakota",
    phone: "297-336-8018 x08645",
    email: "Nicklaus85@gmail.com",
    website: "https://ready-disagreement.net",
    img: "https://loremflickr.com/640/380/business?lock=4254970119454720",
    banner: "https://loremflickr.com/1200/380/business?lock=4627550798086144",
    discription:
      "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
  },
  {
    id: 50,
    shopName: "target e-business interfaces",
    ownerName: "Stuart Dibbert",
    category: "Plumbing",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Vandervort Wall",
    city: "St. Joseph",
    state: "Massachusetts",
    phone: "408.849.3353 x785",
    email: "Donavon90@yahoo.com",
    website: "https://worried-recommendation.net/",
    img: "https://loremflickr.com/640/380/business?lock=3657176702779392",
    banner: "https://loremflickr.com/1200/380/business?lock=4409817535873024",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 51,
    shopName: "aggregate leading-edge initiatives",
    ownerName: "Shawn Hoppe",
    category: "Delivery",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Carter Spring",
    city: "South Loren",
    state: "Oregon",
    phone: "1-975-635-9883 x7999",
    email: "Mohamed71@gmail.com",
    website: "https://whirlwind-quest.com/",
    img: "https://loremflickr.com/640/380/business?lock=4211833810452480",
    banner: "https://loremflickr.com/1200/380/business?lock=5306779655208960",
    discription:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
  },
  {
    id: 52,
    shopName: "aggregate web-enabled metrics",
    ownerName: "Dr. Luz Ankunding",
    category: "Plumbing",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Anastacio Squares",
    city: "South Ryley",
    state: "West Virginia",
    phone: "1-490-813-3322",
    email: "Dorian.Klocko89@yahoo.com",
    website: "https://nautical-pomelo.net",
    img: "https://loremflickr.com/640/380/business?lock=4383306902667264",
    banner: "https://loremflickr.com/1200/380/business?lock=2338188664242176",
    discription:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
  },
  {
    id: 53,
    shopName: "target vertical users",
    ownerName: "Denise Green",
    category: "Delivery",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Cherry Close",
    city: "Hahncester",
    state: "New York",
    phone: "611-498-6181 x2691",
    email: "Eliza8@gmail.com",
    website: "https://emotional-phrase.net/",
    img: "https://loremflickr.com/640/380/business?lock=1321592858607616",
    banner: "https://loremflickr.com/1200/380/business?lock=6446035322798080",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 54,
    shopName: "matrix frictionless users",
    ownerName: "Mr. Leon Lemke",
    category: "Plumbing",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Stamm Union",
    city: "Port Hermina",
    state: "Virginia",
    phone: "(352) 223-5395",
    email: "Fletcher_Brakus41@hotmail.com",
    website: "https://pleasant-railway.net",
    img: "https://loremflickr.com/640/380/business?lock=8800642564882432",
    banner: "https://loremflickr.com/1200/380/business?lock=6863217292738560",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 55,
    shopName: "harness enterprise e-business",
    ownerName: "Chris Schneider",
    category: "Auto Services",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Zemlak Run",
    city: "Southfield",
    state: "South Carolina",
    phone: "1-639-994-8363 x463",
    email: "Jessy_Kuphal@yahoo.com",
    website: "https://focused-stir-fry.name",
    img: "https://loremflickr.com/640/380/business?lock=8548195722330112",
    banner: "https://loremflickr.com/1200/380/business?lock=8438955382931456",
    discription:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
  },
  {
    id: 56,
    shopName: "evolve integrated content",
    ownerName: "Dora Simonis-Johns",
    category: "Delivery",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Sherman Wall",
    city: "South Lina",
    state: "Mississippi",
    phone: "287.310.3408",
    email: "Nico.Grimes@gmail.com",
    website: "https://bland-past.biz/",
    img: "https://loremflickr.com/640/380/business?lock=2005279944212480",
    banner: "https://loremflickr.com/1200/380/business?lock=6220613278498816",
    discription:
      "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
  },
  {
    id: 57,
    shopName: "harness turn-key lifetime value",
    ownerName: "Gwendolyn Koelpin",
    category: "Auto Services",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Ash Road",
    city: "West Cleveland",
    state: "Oregon",
    phone: "311.928.2008",
    email: "Dillon_Reilly94@yahoo.com",
    website: "https://dear-realm.biz",
    img: "https://loremflickr.com/640/380/business?lock=5163017914286080",
    banner: "https://loremflickr.com/1200/380/business?lock=5672707251240960",
    discription:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
  },
  {
    id: 58,
    shopName: "revolutionize global action-items",
    ownerName: "Randall Feil",
    category: "Plumbing",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Heather Close",
    city: "Josephfurt",
    state: "Illinois",
    phone: "(425) 959-6135 x72581",
    email: "Ed88@gmail.com",
    website: "https://mellow-arrow.biz/",
    img: "https://loremflickr.com/640/380/business?lock=2484195528015872",
    banner: "https://loremflickr.com/1200/380/business?lock=1134327976951808",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 59,
    shopName: "evolve frictionless synergies",
    ownerName: "Troy Schumm",
    category: "Restaurant",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "N 8th Street",
    city: "East Emmett",
    state: "Oklahoma",
    phone: "(492) 450-1343 x58998",
    email: "Paxton40@gmail.com",
    website: "https://polite-midnight.org/",
    img: "https://loremflickr.com/640/380/business?lock=540360033959936",
    banner: "https://loremflickr.com/1200/380/business?lock=3754379985289216",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 60,
    shopName: "morph wireless users",
    ownerName: "Edmund Bergnaum",
    category: "Delivery",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Karina Circles",
    city: "New Cullen",
    state: "Arizona",
    phone: "550.811.4598 x91727",
    email: "Bernhard_Tromp25@yahoo.com",
    website: "https://zesty-viscose.com/",
    img: "https://loremflickr.com/640/380/business?lock=8645287912407040",
    banner: "https://loremflickr.com/1200/380/business?lock=985477920325632",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 61,
    shopName: "transform plug-and-play schemas",
    ownerName: "Trevor Hodkiewicz",
    category: "Home Services",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Narciso Roads",
    city: "Destineestead",
    state: "Maryland",
    phone: "(435) 259-8163 x2167",
    email: "Triston.Wisozk@yahoo.com",
    website: "https://embellished-overweight.biz/",
    img: "https://loremflickr.com/640/380/business?lock=2323503554494464",
    banner: "https://loremflickr.com/1200/380/business?lock=6241013064531968",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 62,
    shopName: "streamline one-to-one methodologies",
    ownerName: "Gail Rath",
    category: "Restaurant",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Walker Flats",
    city: "Valdosta",
    state: "Iowa",
    phone: "(600) 462-8874",
    email: "Maybell57@hotmail.com",
    website: "https://rowdy-sunbeam.com/",
    img: "https://loremflickr.com/640/380/business?lock=2012468800913408",
    banner: "https://loremflickr.com/1200/380/business?lock=1980948434386944",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 63,
    shopName: "harness dynamic e-commerce",
    ownerName: "Lori Reichert-Luettgen",
    category: "Auto Services",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Manor Way",
    city: "Halvorsonberg",
    state: "Kansas",
    phone: "468-711-8353",
    email: "Katarina.Schoen@gmail.com",
    website: "https://better-tourist.info",
    img: "https://loremflickr.com/640/380/business?lock=5768724644626432",
    banner: "https://loremflickr.com/1200/380/business?lock=8589069820887040",
    discription:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
  },
  {
    id: 64,
    shopName: "integrate customized content",
    ownerName: "Ms. Kerry Friesen",
    category: "Plumbing",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Jefferson Avenue",
    city: "East Jeanie",
    state: "Nebraska",
    phone: "1-480-242-1917 x9181",
    email: "Koby72@hotmail.com",
    website: "https://high-level-discrepancy.name",
    img: "https://loremflickr.com/640/380/business?lock=4006417010786304",
    banner: "https://loremflickr.com/1200/380/business?lock=2727317679898624",
    discription:
      "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
  },
  {
    id: 65,
    shopName: "morph dynamic functionalities",
    ownerName: "Dr. Johnnie Mertz",
    category: "Restaurant",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Lebsack Estate",
    city: "Port Arthur",
    state: "South Carolina",
    phone: "497.493.5937 x6335",
    email: "Alayna.Carter@gmail.com",
    website: "https://sardonic-commotion.name/",
    img: "https://loremflickr.com/640/380/business?lock=5398257427546112",
    banner: "https://loremflickr.com/1200/380/business?lock=3245995760549888",
    discription:
      "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
  },
  {
    id: 66,
    shopName: "utilize impactful paradigms",
    ownerName: "Dr. Edwin Lindgren",
    category: "Auto Services",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Kozey Place",
    city: "Port Keyon",
    state: "Texas",
    phone: "449-309-0892 x9439",
    email: "Enoch.Bednar@gmail.com",
    website: "https://impolite-chromolithograph.org/",
    img: "https://loremflickr.com/640/380/business?lock=527993667584000",
    banner: "https://loremflickr.com/1200/380/business?lock=3925883706408960",
    discription:
      "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
  },
  {
    id: 67,
    shopName: "visualize holistic channels",
    ownerName: "Marion Moore",
    category: "Home Services",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Frontage Road",
    city: "Allentown",
    state: "New Jersey",
    phone: "(274) 481-4460 x7326",
    email: "Jamison89@hotmail.com",
    website: "https://fixed-styling.com/",
    img: "https://loremflickr.com/640/380/business?lock=4903622410240000",
    banner: "https://loremflickr.com/1200/380/business?lock=1076421275418624",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 68,
    shopName: "streamline collaborative e-markets",
    ownerName: "Willard Quigley-Schumm III",
    category: "Restaurant",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Haag Green",
    city: "Fort Jodie",
    state: "Washington",
    phone: "940.378.8503",
    email: "Elsie_Marquardt65@gmail.com",
    website: "https://wide-steak.org",
    img: "https://loremflickr.com/640/380/business?lock=704687596634112",
    banner: "https://loremflickr.com/1200/380/business?lock=2492717399539712",
    discription:
      "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
  },
  {
    id: 69,
    shopName: "exploit collaborative e-markets",
    ownerName: "Leona Gerlach",
    category: "Home Services",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Cedar Avenue",
    city: "Schoenfield",
    state: "Connecticut",
    phone: "(892) 884-4113 x510",
    email: "Abigale.Hansen77@hotmail.com",
    website: "https://overcooked-boycott.info/",
    img: "https://loremflickr.com/640/380/business?lock=3080474261979136",
    banner: "https://loremflickr.com/1200/380/business?lock=5863320387059712",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 70,
    shopName: "mesh cross-media relationships",
    ownerName: "Ruben Herzog",
    category: "Delivery",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Meadow Close",
    city: "Maximomouth",
    state: "Wyoming",
    phone: "(953) 528-7912 x666",
    email: "Loma.Cormier38@gmail.com",
    website: "https://serpentine-temperature.net",
    img: "https://loremflickr.com/640/380/business?lock=7882082470592512",
    banner: "https://loremflickr.com/1200/380/business?lock=3618603718934528",
    discription:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
  },
  {
    id: 71,
    shopName: "cultivate cross-platform paradigms",
    ownerName: "Mildred Funk",
    category: "Delivery",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Bogisich Freeway",
    city: "Keeblertown",
    state: "South Dakota",
    phone: "(702) 769-9776 x39467",
    email: "Ed.Feeney77@hotmail.com",
    website: "https://striped-plaster.name",
    img: "https://loremflickr.com/640/380/business?lock=4632444590358528",
    banner: "https://loremflickr.com/1200/380/business?lock=7471048146550784",
    discription:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
  },
  {
    id: 72,
    shopName: "streamline global e-commerce",
    ownerName: "Miss Pat Hayes",
    category: "Home Services",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Alessandra Union",
    city: "Cleveland Heights",
    state: "Nevada",
    phone: "769.475.0137",
    email: "Theodore48@gmail.com",
    website: "https://frequent-adult.name/",
    img: "https://loremflickr.com/640/380/business?lock=6283531579817984",
    banner: "https://loremflickr.com/1200/380/business?lock=6224935607336960",
    discription:
      "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
  },
  {
    id: 73,
    shopName: "monetize web-enabled content",
    ownerName: "Eileen Tremblay",
    category: "Auto Services",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "St Mary's Road",
    city: "New Dylanchester",
    state: "Louisiana",
    phone: "403-599-0144 x10105",
    email: "Tristian9@hotmail.com",
    website: "https://open-baseball.info/",
    img: "https://loremflickr.com/640/380/business?lock=7241483488854016",
    banner: "https://loremflickr.com/1200/380/business?lock=8938271044272128",
    discription:
      "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
  },
  {
    id: 74,
    shopName: "architect 24/7 platforms",
    ownerName: "Marta Heaney",
    category: "Plumbing",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Olson Brook",
    city: "North Ofelia",
    state: "Ohio",
    phone: "945.936.4342 x1263",
    email: "Violet.Walsh50@hotmail.com",
    website: "https://fuzzy-uncle.org",
    img: "https://loremflickr.com/640/380/business?lock=4365177306742784",
    banner: "https://loremflickr.com/1200/380/business?lock=4111513468010496",
    discription:
      "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
  },
  {
    id: 75,
    shopName: "architect magnetic infrastructures",
    ownerName: "Myra Marquardt",
    category: "Auto Services",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "The Poplars",
    city: "South Zoie",
    state: "Mississippi",
    phone: "417-617-6901",
    email: "Emmet.Wuckert@yahoo.com",
    website: "https://enraged-hearthside.biz",
    img: "https://loremflickr.com/640/380/business?lock=4702733789560832",
    banner: "https://loremflickr.com/1200/380/business?lock=8743529702490112",
    discription:
      "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
  },
  {
    id: 76,
    shopName: "matrix web-enabled metrics",
    ownerName: "Sue Nicolas",
    category: "Plumbing",
    services: ["Cleaning", "Repairs", "Installation"],
    address: "Neva Court",
    city: "Kozeyport",
    state: "New Mexico",
    phone: "1-318-932-4774",
    email: "Arnold_Legros54@gmail.com",
    website: "https://warlike-maniac.name/",
    img: "https://loremflickr.com/640/380/business?lock=7085514574266368",
    banner: "https://loremflickr.com/1200/380/business?lock=4539372166709248",
    discription:
      "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
  },
  {
    id: 77,
    shopName: "engage back-end applications",
    ownerName: "Hilda Muller I",
    category: "Auto Services",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Daisy Well",
    city: "Millsburgh",
    state: "Georgia",
    phone: "814-981-4287 x43447",
    email: "Mozell27@hotmail.com",
    website: "https://limited-fitness.org/",
    img: "https://loremflickr.com/640/380/business?lock=351643860205568",
    banner: "https://loremflickr.com/1200/380/business?lock=273383428194304",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 78,
    shopName: "exploit cutting-edge web services",
    ownerName: "Marianne Johnson MD",
    category: "Auto Services",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Waelchi Knolls",
    city: "Dachworth",
    state: "Nevada",
    phone: "(990) 633-3077",
    email: "Dock33@yahoo.com",
    website: "https://dimpled-scrim.org/",
    img: "https://loremflickr.com/640/380/business?lock=94352346972160",
    banner: "https://loremflickr.com/1200/380/business?lock=5187683110354944",
    discription:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
  },
  {
    id: 79,
    shopName: "e-enable mission-critical lifetime value",
    ownerName: "Noah Gottlieb DDS",
    category: "Restaurant",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Corene Underpass",
    city: "Fremont",
    state: "Arkansas",
    phone: "(745) 668-7998",
    email: "Americo_Nienow@hotmail.com",
    website: "https://acrobatic-date.net/",
    img: "https://loremflickr.com/640/380/business?lock=7139960217927680",
    banner: "https://loremflickr.com/1200/380/business?lock=7675537839357952",
    discription:
      "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
  },
  {
    id: 80,
    shopName: "productize collaborative deliverables",
    ownerName: "Kerry Skiles",
    category: "Auto Services",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Dandre Alley",
    city: "Johnsonhaven",
    state: "Virginia",
    phone: "(625) 529-2901 x54485",
    email: "Adelbert.OHara@gmail.com",
    website: "https://negative-regime.org/",
    img: "https://loremflickr.com/640/380/business?lock=8879866631946240",
    banner: "https://loremflickr.com/1200/380/business?lock=2440410056097792",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 81,
    shopName: "target real-time relationships",
    ownerName: "Judy Langworth",
    category: "Auto Services",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Ridge Road",
    city: "Beahanworth",
    state: "Connecticut",
    phone: "(760) 493-7874 x4451",
    email: "Ericka23@hotmail.com",
    website: "https://miserable-mobile.biz",
    img: "https://loremflickr.com/640/380/business?lock=3063022910177280",
    banner: "https://loremflickr.com/1200/380/business?lock=4145584600514560",
    discription:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
  },
  {
    id: 82,
    shopName: "embrace holistic blockchains",
    ownerName: "Mr. Ramon Hettinger",
    category: "Plumbing",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Blanche Groves",
    city: "New Theodora",
    state: "North Carolina",
    phone: "(779) 672-7727 x062",
    email: "Mathias_White94@hotmail.com",
    website: "https://subdued-teletype.biz",
    img: "https://loremflickr.com/640/380/business?lock=3638670273806336",
    banner: "https://loremflickr.com/1200/380/business?lock=3648087335632896",
    discription:
      "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
  },
  {
    id: 83,
    shopName: "transition open-source eyeballs",
    ownerName: "Lawrence Bode",
    category: "Restaurant",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Carroll Branch",
    city: "New Brooksshire",
    state: "Arkansas",
    phone: "341.577.2746 x1252",
    email: "Obie.Buckridge34@hotmail.com",
    website: "https://notable-vibraphone.com",
    img: "https://loremflickr.com/640/380/business?lock=2943950451113984",
    banner: "https://loremflickr.com/1200/380/business?lock=5601196693782528",
    discription:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
  },
  {
    id: 84,
    shopName: "aggregate B2B solutions",
    ownerName: "Courtney Kemmer",
    category: "Delivery",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Keebler Row",
    city: "Kilbackfield",
    state: "Utah",
    phone: "1-508-881-9390",
    email: "Dawn.Wunsch94@hotmail.com",
    website: "https://same-thunderstorm.com",
    img: "https://loremflickr.com/640/380/business?lock=4878636479938560",
    banner: "https://loremflickr.com/1200/380/business?lock=7431609793904640",
    discription:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
  },
  {
    id: 85,
    shopName: "orchestrate plug-and-play e-commerce",
    ownerName: "Miss Iris Swift",
    category: "Home Services",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Fae Corner",
    city: "Fort Madisen",
    state: "Rhode Island",
    phone: "(447) 599-0813 x0898",
    email: "Marianne.Williamson64@hotmail.com",
    website: "https://indelible-foreigner.biz",
    img: "https://loremflickr.com/640/380/business?lock=2247437922074624",
    banner: "https://loremflickr.com/1200/380/business?lock=4596907938676736",
    discription:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
  },
  {
    id: 86,
    shopName: "empower out-of-the-box e-commerce",
    ownerName: "Orlando Mueller",
    category: "Home Services",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Sycamore Avenue",
    city: "Jalynberg",
    state: "Arizona",
    phone: "362.641.3660 x82195",
    email: "Libby48@hotmail.com",
    website: "https://red-eyebrow.biz",
    img: "https://loremflickr.com/640/380/business?lock=6760948639465472",
    banner: "https://loremflickr.com/1200/380/business?lock=3350623535759360",
    discription:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  },
  {
    id: 87,
    shopName: "seize end-to-end architectures",
    ownerName: "Constance VonRueden",
    category: "Restaurant",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Poplar Road",
    city: "East Clemens",
    state: "Idaho",
    phone: "1-469-612-8543 x668",
    email: "Matt40@gmail.com",
    website: "https://stained-webmail.org",
    img: "https://loremflickr.com/640/380/business?lock=8277572634804224",
    banner: "https://loremflickr.com/1200/380/business?lock=7885313410072576",
    discription:
      "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
  },
  {
    id: 88,
    shopName: "innovate cutting-edge markets",
    ownerName: "Louise Ferry II",
    category: "Restaurant",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "W Division Street",
    city: "New Dannymouth",
    state: "California",
    phone: "1-361-658-3641 x71493",
    email: "Gussie98@gmail.com",
    website: "https://descriptive-swim.com",
    img: "https://loremflickr.com/640/380/business?lock=2195453047209984",
    banner: "https://loremflickr.com/1200/380/business?lock=6508045804765184",
    discription:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
  },
  {
    id: 89,
    shopName: "exploit 24/365 markets",
    ownerName: "Lindsay Mosciski-Upton",
    category: "Auto Services",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Chester Islands",
    city: "Hermanshire",
    state: "Missouri",
    phone: "1-404-574-6435 x66597",
    email: "Summer_Ondricka@gmail.com",
    website: "https://forked-spool.com",
    img: "https://loremflickr.com/640/380/business?lock=8887769069780992",
    banner: "https://loremflickr.com/1200/380/business?lock=277821897310208",
    discription:
      "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
  },
  {
    id: 90,
    shopName: "matrix revolutionary solutions",
    ownerName: "Robyn Lockman",
    category: "Auto Services",
    services: ["Dry Cleaning", "Laundry", "Alterations"],
    address: "Toy Walks",
    city: "Altamonte Springs",
    state: "Arkansas",
    phone: "746.993.4698 x02050",
    email: "Eulalia_Lindgren@hotmail.com",
    website: "https://funny-wetsuit.biz/",
    img: "https://loremflickr.com/640/380/business?lock=1254969864880128",
    banner: "https://loremflickr.com/1200/380/business?lock=6297470344626176",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 91,
    shopName: "evolve B2C eyeballs",
    ownerName: "Kimberly Will",
    category: "Restaurant",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Hirthe Common",
    city: "Lake Jalonfurt",
    state: "Iowa",
    phone: "1-281-448-6318",
    email: "Sonya_Jones84@hotmail.com",
    website: "https://sparse-bread.info",
    img: "https://loremflickr.com/640/380/business?lock=1258709737013248",
    banner: "https://loremflickr.com/1200/380/business?lock=3598644898955264",
    discription:
      "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
  },
  {
    id: 92,
    shopName: "incentivize 24/365 paradigms",
    ownerName: "Lowell Beatty",
    category: "Restaurant",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Dewitt Oval",
    city: "Buckhaven",
    state: "Wyoming",
    phone: "1-399-874-7181 x8918",
    email: "Vernice_Morar@yahoo.com",
    website: "https://double-stage.name/",
    img: "https://loremflickr.com/640/380/business?lock=8098000681304064",
    banner: "https://loremflickr.com/1200/380/business?lock=5117828092919808",
    discription:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
  },
  {
    id: 93,
    shopName: "drive magnetic action-items",
    ownerName: "Rudolph Boyer",
    category: "Dry Cleaning",
    services: ["Pipe Repair", "Drain Cleaning", "Fixture Installation"],
    address: "Henri Track",
    city: "Tristinchester",
    state: "Connecticut",
    phone: "772.510.8804",
    email: "Adrianna.Haag@yahoo.com",
    website: "https://milky-synthesis.org/",
    img: "https://loremflickr.com/640/380/business?lock=2392339240714240",
    banner: "https://loremflickr.com/1200/380/business?lock=4088192626065408",
    discription:
      "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
  },
  {
    id: 94,
    shopName: "iterate real-time infrastructures",
    ownerName: "Tommy Johns",
    category: "Home Services",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Boyer Run",
    city: "South Ruthiestead",
    state: "Nevada",
    phone: "1-863-470-7927 x4927",
    email: "Bonita95@hotmail.com",
    website: "https://sunny-documentation.info",
    img: "https://loremflickr.com/640/380/business?lock=450512478535680",
    banner: "https://loremflickr.com/1200/380/business?lock=42560072450048",
    discription:
      "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
  },
  {
    id: 95,
    shopName: "incentivize dot-com users",
    ownerName: "Jan Moore",
    category: "Plumbing",
    services: ["Courier Service", "Food Delivery", "Package Delivery"],
    address: "Matteo Landing",
    city: "Adamston",
    state: "Iowa",
    phone: "376-955-2759 x5781",
    email: "Ray41@gmail.com",
    website: "https://wasteful-tripod.name",
    img: "https://loremflickr.com/640/380/business?lock=105405403365376",
    banner: "https://loremflickr.com/1200/380/business?lock=1276215780442112",
    discription:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
  },
  {
    id: 96,
    shopName: "iterate dot-com solutions",
    ownerName: "Perry Franey",
    category: "Restaurant",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "West Avenue",
    city: "New Leone",
    state: "Georgia",
    phone: "960-207-1252 x7048",
    email: "Whitney.Kub@hotmail.com",
    website: "https://spherical-spec.org",
    img: "https://loremflickr.com/640/380/business?lock=8866779413610496",
    banner: "https://loremflickr.com/1200/380/business?lock=4430938400358400",
    discription:
      "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
  },
  {
    id: 97,
    shopName: "aggregate strategic interfaces",
    ownerName: "Dana Heaney",
    category: "Plumbing",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "McGlynn Crescent",
    city: "Ullrichfort",
    state: "Iowa",
    phone: "1-233-941-6930 x86820",
    email: "Jerod_Klein4@gmail.com",
    website: "https://good-trailer.com",
    img: "https://loremflickr.com/640/380/business?lock=7041420487557120",
    banner: "https://loremflickr.com/1200/380/business?lock=7762256435609600",
    discription: "The Football Is Good For Training And Recreational Purposes",
  },
  {
    id: 98,
    shopName: "engineer killer content",
    ownerName: "Rochelle Boehm",
    category: "Dry Cleaning",
    services: ["Dine-in", "Takeout", "Delivery"],
    address: "Wisoky Green",
    city: "West Jalonville",
    state: "Louisiana",
    phone: "906-474-2124 x3579",
    email: "Wilber.Kutch@hotmail.com",
    website: "https://unlined-lender.net",
    img: "https://loremflickr.com/640/380/business?lock=2578960172974080",
    banner: "https://loremflickr.com/1200/380/business?lock=6424846598668288",
    discription:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
  },
  {
    id: 99,
    shopName: "expedite strategic convergence",
    ownerName: "May Towne",
    category: "Restaurant",
    services: ["Oil Change", "Tire Rotation", "Brake Inspection"],
    address: "Veterans Memorial Highway",
    city: "Port Jermainehaven",
    state: "New Mexico",
    phone: "707.886.1973 x3901",
    email: "Shanelle_Hermiston68@gmail.com",
    website: "https://needy-severity.biz/",
    img: "https://loremflickr.com/640/380/business?lock=4491915397431296",
    banner: "https://loremflickr.com/1200/380/business?lock=8042559458770944",
    discription:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
  },
];
